/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DungThuRouteImport } from './routes/dung-thu'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DungThuRoute = DungThuRouteImport.update({
  id: '/dung-thu',
  path: '/dung-thu',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dung-thu': typeof DungThuRoute
  '/gioi-thieu': typeof GioiThieuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dung-thu': typeof DungThuRoute
  '/gioi-thieu': typeof GioiThieuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dung-thu': typeof DungThuRoute
  '/gioi-thieu': typeof GioiThieuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dung-thu' | '/gioi-thieu'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dung-thu' | '/gioi-thieu'
  id: '__root__' | '/' | '/dung-thu' | '/gioi-thieu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DungThuRoute: typeof DungThuRoute
  GioiThieuRoute: typeof GioiThieuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dung-thu': {
      id: '/dung-thu'
      path: '/dung-thu'
      fullPath: '/dung-thu'
      preLoaderRoute: typeof DungThuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DungThuRoute: DungThuRoute,
  GioiThieuRoute: GioiThieuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
